import getCFDBaseURL from 'config/getCFDBaseURL';

export const backEndTechStack = [
  {
    name: 'Python Logomark',
    link: 'https://www.python.org/psf/trademarks/',
    imageSrc: getCFDBaseURL('/assets/images/python-logomark.svg'),
    progressBarLimit: 'w-4/5',
    gradientColorFrom: 'from-[#366994]',
    gradientColorTo: 'to-[#FFC331]',
    textColor: 'text-black',
    progress: '80',
  },
  {
    name: 'C++ Logomark',
    link: 'https://cplusplus.com/',
    imageSrc: getCFDBaseURL('/assets/images/c-plus-plus-logomark.svg'),
    progressBarLimit: 'w-3/5',
    gradientColorFrom: 'from-[#659AD2]',
    gradientColorTo: 'to-[#00599C]',
    textColor: 'text-white',
    progress: '60',
  },
  {
    name: 'C# Logomark',
    link: 'https://learn.microsoft.com/en-us/dotnet/csharp/',
    imageSrc: getCFDBaseURL('/assets/images/c-sharp-logomark.svg'),
    progressBarLimit: 'w-2/5',
    gradientColorFrom: 'from-fuchsia-600',
    gradientColorTo: 'to-purple-400',
    textColor: 'text-white',
    progress: '40',
  },
  {
    name: 'NodeJS Logomark',
    link: 'https://nodejs.dev/en/about/branding/',
    imageSrc: getCFDBaseURL('/assets/images/node.js-logomark.svg'),
    progressBarLimit: 'w-4/5',
    gradientColorFrom: 'from-[#417E38]',
    gradientColorTo: 'to-[#84BA64]',
    textColor: 'text-black',
    progress: '80',
  },
  {
    name: 'SQL Logomark',
    link: 'https://aws.amazon.com/what-is/sql/',
    imageSrc: getCFDBaseURL('/assets/images/sql-logomark.svg'),
    progressBarLimit: 'w-3/5',
    gradientColorFrom: 'from-[#00BCF2]',
    gradientColorTo: 'to-cyan-600',
    textColor: 'text-black',
    progress: '60',
  },
  {
    name: 'PostgreSQL Logomark',
    link: 'https://www.postgresql.org/about/policies/trademarks/',
    imageSrc: getCFDBaseURL('/assets/images/postgresql-logomark.svg'),
    progressBarLimit: 'w-3/5',
    gradientColorFrom: 'from-[#336791]',
    gradientColorTo: 'to-[#336791]',
    textColor: 'text-white',
    progress: '60',
  },
  {
    name: 'MongoDB Logomark',
    link: 'https://www.mongodb.com/brand-resources/',
    imageSrc: getCFDBaseURL('/assets/images/mongodb-logomark-forest-green.svg'),
    progressBarLimit: 'w-3/5',
    gradientColorFrom: 'from-[#00684A]',
    gradientColorTo: 'to-[#023430]',
    textColor: 'text-white',
    progress: '60',
  },
  {
    name: 'Vercel Logotype',
    link: 'https://vercel.com/design/brands',
    imageSrc: getCFDBaseURL('/assets/images/vercel-logotype.svg'),
    progressBarLimit: 'w-3/5',
    gradientColorFrom: 'from-neutral-200',
    gradientColorTo: 'to-neutral-900/60',
    textColor: 'text-black',
    progress: '60',
  },
];
