import getCFDBaseURL from 'config/getCFDBaseURL';

export const frontEndTechStack = [
  {
    name: 'HTML5 Logomark',
    link: 'https://html.spec.whatwg.org/',
    imageSrc: getCFDBaseURL('/assets/images/html5-logomark.svg'),
    progressBarLimit: 'w-full',
    gradientColorFrom: 'from-red-600',
    gradientColorTo: 'to-orange-400',
    textColor: 'text-white',
    progress: '100',
  },
  {
    name: 'CSS3 Logomark',
    link: 'https://www.w3.org/Style/CSS/Overview.en.html',
    imageSrc: getCFDBaseURL('/assets/images/css3-logomark.svg'),
    progressBarLimit: 'w-full',
    gradientColorFrom: 'from-blue-800',
    gradientColorTo: 'to-blue-400',
    textColor: 'text-white',
    progress: '100',
  },
  {
    name: 'TailwindCSS Logomark',
    link: 'https://tailwindcss.com/brand/',
    imageSrc: getCFDBaseURL('/assets/images/tailwindcss-logomark.svg'),
    progressBarLimit: 'w-full',
    gradientColorFrom: 'from-sky-600',
    gradientColorTo: 'to-[#38BDF8]',
    textColor: 'text-white',
    progress: '100',
  },
  {
    name: 'JavaScript Logomark',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/',
    imageSrc: getCFDBaseURL('/assets/images/javascript-logomark.svg'),
    progressBarLimit: 'w-3/4',
    gradientColorFrom: 'from-yellow-400',
    gradientColorTo: 'to-yellow-200',
    textColor: 'text-black',
    progress: '75',
  },
  {
    name: 'TypeScript Logomark',
    link: 'https://www.typescriptlang.org/branding/',
    imageSrc: getCFDBaseURL('/assets/images/typescript-logomark.svg'),
    progressBarLimit: 'w-3/4',
    gradientColorFrom: 'from-[#3178C6]',
    gradientColorTo: 'to-[#358EF1]',
    textColor: 'text-white',
    progress: '75',
  },
  {
    name: 'React Logomark',
    link: 'https://react.dev/',
    imageSrc: getCFDBaseURL('/assets/images/react-logomark.svg'),
    progressBarLimit: 'w-3/4',
    gradientColorFrom: 'from-[#087EA4]',
    gradientColorTo: 'to-[#087EA4]',
    textColor: 'text-white',
    progress: '75',
  },
  {
    name: 'Next.js Logotype',
    link: 'https://nextjs.org/',
    imageSrc: getCFDBaseURL('/assets/images/next.js-logotype.svg'),
    progressBarLimit: 'w-3/4',
    gradientColorFrom: 'from-neutral-200',
    gradientColorTo: 'to-neutral-900/60',
    textColor: 'text-black',
    progress: '75',
  },
];
